### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by hardware** [Freeaqingme/ClueGetter#12]
Hi,

First, nice work, your tool looks promising ! :+1: 

Can you provide a debian package (.deb) and PGP signature (e.g. cluegetter-0.6.0.deb &
cluegetter-0.6.0.deb.asc) for the current and next releases ? I plan to integrate your tool in my docker image. 

https://github.com/hardware/mailserver

Thank.

**Comment by denji** [comment]
https://packagecloud.io (OSS — 25 GB Storage / 250 GB Bandwidth)

> https://packagecloud.io/docs#os_distro_version LTS and non-LTS deb/rpm/etc…
> elementary OS / Raspbian / Ubuntu / Debian / SUSE Linux Enterprise Server / openSUSE / Fedora / LinuxMint / poky distro / Oracle Linux / Scientific Linux / Enterprise Linux (CentOS, RedHat, Amazon Linux)

**Comment by Freeaqingme** [comment]
I'll see if I can set up some repo this week. Will keep you posted.

**Comment by denji** [comment]
Is there any news?

**Comment by Freeaqingme** [comment]
I expected to find some time much earlier. Obviously that didn't happen and I'm again expecting to finish it in the next few days.

**Comment by Freeaqingme** [comment]
I just set up a basic Debian repository. It only contains tagged releases (for the moment), but I will make a release more often from now on, so you don't miss out :) Please be aware though that ClueGetter is still in beta and still has some rough edges. Having said that, the biggest installation I know of handles 5-10 million messages per day, so it is already rather stable.


```
wget -q -O - http://apt.cluegetter.net/archive.key | sudo apt-key add -
echo 'deb http://apt.cluegetter.net/ jessie main' | sudo tee /etc/apt/sources.list.d/cluegetter.list
sudo apt-get update
sudo apt-get install cluegetter
```

Looking forward to your feedback!

**Comment by hardware** [comment]
Thanks @Freeaqingme. Can you make this package to be compatible with docker ? I got this error with my [dockerfile](https://github.com/hardware/mailserver/blob/master/Dockerfile) :

```
...
&& wget -q -O - http://apt.cluegetter.net/archive.key | apt-key add - \
&& echo 'deb http://apt.cluegetter.net/ jessie main' > /etc/apt/sources.list.d/cluegetter.list \
&& apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -q cluegetter \
...

The following NEW packages will be installed:
  cluegetter
0 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 5012 kB of archives.
After this operation, 18.4 MB of additional disk space will be used.
Get:1 http://apt.cluegetter.net/ jessie/main cluegetter amd64 0.6.0 [5012 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 5012 kB in 1s (2520 kB/s)
Selecting previously unselected package cluegetter.
(Reading database ... 14525 files and directories currently installed.)
Preparing to unpack .../cluegetter_0.6.0_amd64.deb ...
Unpacking cluegetter (0.6.0) ...
Setting up cluegetter (0.6.0) ...
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package cluegetter (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 cluegetter
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I think the D-Bus error is related to Systemd, I use supervisord as process manager in the container, you should not make your package systemd-dependent.

https://github.com/docker/docker/issues/7459
https://github.com/hardware/mailserver/issues/56

Thanks :)

**Comment by Freeaqingme** [comment]
@hardware I currently only run Debian 8 + Systemd systems. Having said that, I'm more than open to also support other service managers. Do you think you'd be able to do some hacking on https://github.com/Freeaqingme/ClueGetter/blob/develop/dist/debian/postinst and file a merge request?

I was just looking around a bit, and see other postinst scripts simply check if a /bin/systemctl binary exists. Such a strategy could work here as well. I have no clue if that's the officially recommended way though :)
